version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=db

    ports:
      - "5432:5432"
    volumes:
      - "db:/var/lib/postgresql"
    networks:
      - ace
  app:
    platform: "linux/amd64"
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "3000:3000"
    image: t3-app
    env_file:
      - .env
    networks:
      - ace
volumes:
  db:
networks:
  ace:
    driver: bridge