version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    volumes:
      - "db:/var/lib/postgresql"
volumes:
  db: